# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_student_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QMessageBox

from university_management.src.controller.major_management.get_major import get_all_major, get_major_id
from university_management.src.controller.user_management.UserCommand import Invoker, CreateUserCommand
from university_management.src.database.initSession import session
from university_management.src.model.Model import User


class Ui_add_student_dialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("add_student_dialog")
        self.resize(466, 517)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.setFont(font)
        self.setStyleSheet("QDialog {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid rgb(31, 149, 239);\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"QDateEdit {\n"
"    border: 1px solid rgb(31, 149, 239);\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 31px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid rgb(31, 149, 239);\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 31px;\n"
"}")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(20, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self)
        self.line.setGeometry(QtCore.QRect(0, 60, 461, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 441, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.studentIDEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.studentIDEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.studentIDEdit.setObjectName("studentIDEdit")
        self.verticalLayout.addWidget(self.studentIDEdit)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.gender_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.gender_comboBox.setObjectName("gender_comboBox")
        self.gender_comboBox.addItem("")
        self.gender_comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.gender_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.major_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.major_comboBox.setObjectName("major_comboBox")
        major_list = get_all_major()
        print(len(major_list))
        for major in major_list:
            self.major_comboBox.addItem(major)
        self.verticalLayout_3.addWidget(self.major_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.studentNameEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.studentNameEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.studentNameEdit.setObjectName("studentNameEdit")
        self.verticalLayout_5.addWidget(self.studentNameEdit)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.studentPhoneEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.studentPhoneEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.studentPhoneEdit.setObjectName("studentPhoneEdit")
        self.verticalLayout_6.addWidget(self.studentPhoneEdit)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.studentAddressEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.studentAddressEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.studentAddressEdit.setObjectName("studentAddressEdit")
        self.verticalLayout_7.addWidget(self.studentAddressEdit)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.layoutWidget1 = QtWidgets.QWidget(self)
        self.layoutWidget1.setGeometry(QtCore.QRect(250, 460, 201, 43))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.add_Btn.setMinimumSize(QtCore.QSize(0, 41))
        self.add_Btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(31, 149, 239);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}")
        self.add_Btn.setObjectName("add_Btn")
        self.horizontalLayout_2.addWidget(self.add_Btn)
        self.cancel_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.cancel_Btn.setMinimumSize(QtCore.QSize(0, 41))
        self.cancel_Btn.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}")
        self.cancel_Btn.setObjectName("cancel_Btn")
        self.horizontalLayout_2.addWidget(self.cancel_Btn)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        # Add button logic
        self.add_Btn.clicked.connect(self.add_student)
        self.cancel_Btn.clicked.connect(self.close)

    def retranslateUi(self, add_student_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_student_dialog.setWindowTitle(_translate("add_student_dialog", "Dialog"))
        self.label.setText(_translate("add_student_dialog", "Thêm sinh viên mới"))
        self.label_2.setText(_translate("add_student_dialog", "Mã số sinh viên"))
        self.label_5.setText(_translate("add_student_dialog", "Giới tính"))
        self.gender_comboBox.setItemText(0, _translate("add_student_dialog", "Nam"))
        self.gender_comboBox.setItemText(1, _translate("add_student_dialog", "Nữ"))
        self.label_6.setText(_translate("add_student_dialog", "Ngành"))
        self.label_3.setText(_translate("add_student_dialog", "Họ tên"))
        self.label_4.setText(_translate("add_student_dialog", "Số điện thoại"))
        self.label_8.setText(_translate("add_student_dialog", "Địa chỉ"))
        self.add_Btn.setText(_translate("add_student_dialog", "Thêm"))
        self.cancel_Btn.setText(_translate("add_student_dialog", "Hủy"))

    def getFirstAndLastName(self, fullName):
        """
        Cắt họ và tên từ chuỗi họ tên.

        Args:
          chuoi_ho_ten: Chuỗi họ tên dạng "Họ Tên".

        Returns:
          Tuple chứa họ và tên.
        """
        ho_ten = fullName.split()
        if len(ho_ten) > 1:
            return ho_ten[0], " ".join(ho_ten[1:])
        else:
            return None

    def getInfo(self):
        print("Get info...")
        user_info = {
            "User_id": self.studentIDEdit.text(),
            "Password": "1",
            "User_email": self.studentIDEdit.text() + "@gm.uit.edu.vn",
            "User_role": 3
        }
        firstName, lastName = self.getFirstAndLastName(self.studentNameEdit.text())
        student_info = {
            "Student_id": self.studentIDEdit.text(),
            "firstName": firstName,
            "lastName": lastName,
            "telephone": self.studentPhoneEdit.text(),
            "address": self.studentAddressEdit.text(),
            "profile_image": "image",
            "gender": self.get_gender_id(self.gender_comboBox.currentText()),
            "major":  get_major_id(self.major_comboBox.currentText()),
            "credit": 0,
            "year": 1,
        }
        return user_info, student_info

    def get_gender_id(self, gender):
        if gender == "Nam":
            return 1
        elif gender == "Nữ":
            return 2

    def add_new_student(self):
        user_info, student_info = self.getInfo()
        if not self.isUserExist(user_info["User_id"]):
            print("add new student...")
            invoker = Invoker()
            command = CreateUserCommand(user_info, student_info)
            invoker.set_on_start(command)
            invoker.createUser()
            self.show_added_message()

    def isUserExist(self, userID):
        user = session.query(User).get(userID)
        if user:
            return True
        else:
            return False

    def show_added_message(self):
        msg_box = QMessageBox(self)
        msg_box.setWindowTitle("Success")
        msg_box.setText("Đã thêm thành công")
        msg_box.exec()

    def add_student(self):
        self.add_new_student()
        self.accept()