# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_class_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_class_dialog(object):
    def setupUi(self, add_class_dialog):
        add_class_dialog.setObjectName("add_class_dialog")
        add_class_dialog.resize(466, 579)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        add_class_dialog.setFont(font)
        add_class_dialog.setStyleSheet("QDialog {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid rgb(31, 149, 239);\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"QDateEdit {\n"
"    border: 1px solid rgb(31, 149, 239);\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 31px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid rgb(31, 149, 239);\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 31px;\n"
"}")
        self.label = QtWidgets.QLabel(add_class_dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(add_class_dialog)
        self.line.setGeometry(QtCore.QRect(0, 60, 461, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(add_class_dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 441, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.classIDEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.classIDEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.classIDEdit.setObjectName("classIDEdit")
        self.verticalLayout.addWidget(self.classIDEdit)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.semester_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.semester_comboBox.setObjectName("semester_comboBox")
        self.semester_comboBox.addItem("")
        self.semester_comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.semester_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.year_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.year_comboBox.setObjectName("year_comboBox")
        self.year_comboBox.addItem("")
        self.year_comboBox.addItem("")
        self.year_comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.year_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.lecturer_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.lecturer_comboBox.setObjectName("lecturer_comboBox")
        self.verticalLayout_5.addWidget(self.lecturer_comboBox)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.course_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.course_comboBox.setObjectName("course_comboBox")
        self.verticalLayout_6.addWidget(self.course_comboBox)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.startPeriod_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.startPeriod_comboBox.setObjectName("startPeriod_comboBox")
        self.startPeriod_comboBox.addItem("")
        self.startPeriod_comboBox.addItem("")
        self.startPeriod_comboBox.addItem("")
        self.startPeriod_comboBox.addItem("")
        self.startPeriod_comboBox.addItem("")
        self.startPeriod_comboBox.addItem("")
        self.startPeriod_comboBox.addItem("")
        self.startPeriod_comboBox.addItem("")
        self.startPeriod_comboBox.addItem("")
        self.startPeriod_comboBox.addItem("")
        self.verticalLayout_4.addWidget(self.startPeriod_comboBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.endPeriod_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.endPeriod_comboBox.setObjectName("endPeriod_comboBox")
        self.endPeriod_comboBox.addItem("")
        self.endPeriod_comboBox.addItem("")
        self.endPeriod_comboBox.addItem("")
        self.endPeriod_comboBox.addItem("")
        self.endPeriod_comboBox.addItem("")
        self.endPeriod_comboBox.addItem("")
        self.endPeriod_comboBox.addItem("")
        self.endPeriod_comboBox.addItem("")
        self.endPeriod_comboBox.addItem("")
        self.endPeriod_comboBox.addItem("")
        self.verticalLayout_10.addWidget(self.endPeriod_comboBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.day_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.day_comboBox.setObjectName("day_comboBox")
        self.day_comboBox.addItem("")
        self.day_comboBox.addItem("")
        self.day_comboBox.addItem("")
        self.day_comboBox.addItem("")
        self.day_comboBox.addItem("")
        self.day_comboBox.addItem("")
        self.verticalLayout_9.addWidget(self.day_comboBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.layoutWidget1 = QtWidgets.QWidget(add_class_dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(250, 520, 201, 43))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.add_Btn.setMinimumSize(QtCore.QSize(0, 41))
        self.add_Btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(31, 149, 239);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}")
        self.add_Btn.setObjectName("add_Btn")
        self.horizontalLayout_2.addWidget(self.add_Btn)
        self.cancel_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.cancel_Btn.setMinimumSize(QtCore.QSize(0, 41))
        self.cancel_Btn.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}")
        self.cancel_Btn.setObjectName("cancel_Btn")
        self.horizontalLayout_2.addWidget(self.cancel_Btn)

        self.retranslateUi(add_class_dialog)
        QtCore.QMetaObject.connectSlotsByName(add_class_dialog)

    def retranslateUi(self, add_class_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_class_dialog.setWindowTitle(_translate("add_class_dialog", "Dialog"))
        self.label.setText(_translate("add_class_dialog", "Thêm lớp học mới"))
        self.label_2.setText(_translate("add_class_dialog", "Tên lớp học"))
        self.label_5.setText(_translate("add_class_dialog", "Kì"))
        self.semester_comboBox.setItemText(0, _translate("add_class_dialog", "1"))
        self.semester_comboBox.setItemText(1, _translate("add_class_dialog", "2"))
        self.label_6.setText(_translate("add_class_dialog", "Năm học"))
        self.year_comboBox.setItemText(0, _translate("add_class_dialog", "Công nghệ thông tin"))
        self.year_comboBox.setItemText(1, _translate("add_class_dialog", "Hệ thống thông tin"))
        self.year_comboBox.setItemText(2, _translate("add_class_dialog", "Khoa học máy tính"))
        self.label_3.setText(_translate("add_class_dialog", "Giảng viên"))
        self.label_4.setText(_translate("add_class_dialog", "Môn học"))
        self.label_7.setText(_translate("add_class_dialog", "Tiết bắt đầu"))
        self.startPeriod_comboBox.setItemText(0, _translate("add_class_dialog", "1"))
        self.startPeriod_comboBox.setItemText(1, _translate("add_class_dialog", "2"))
        self.startPeriod_comboBox.setItemText(2, _translate("add_class_dialog", "3"))
        self.startPeriod_comboBox.setItemText(3, _translate("add_class_dialog", "4"))
        self.startPeriod_comboBox.setItemText(4, _translate("add_class_dialog", "5"))
        self.startPeriod_comboBox.setItemText(5, _translate("add_class_dialog", "6"))
        self.startPeriod_comboBox.setItemText(6, _translate("add_class_dialog", "7"))
        self.startPeriod_comboBox.setItemText(7, _translate("add_class_dialog", "8"))
        self.startPeriod_comboBox.setItemText(8, _translate("add_class_dialog", "9"))
        self.startPeriod_comboBox.setItemText(9, _translate("add_class_dialog", "10"))
        self.label_10.setText(_translate("add_class_dialog", "Tiết kết thúc"))
        self.endPeriod_comboBox.setItemText(0, _translate("add_class_dialog", "1"))
        self.endPeriod_comboBox.setItemText(1, _translate("add_class_dialog", "2"))
        self.endPeriod_comboBox.setItemText(2, _translate("add_class_dialog", "3"))
        self.endPeriod_comboBox.setItemText(3, _translate("add_class_dialog", "4"))
        self.endPeriod_comboBox.setItemText(4, _translate("add_class_dialog", "5"))
        self.endPeriod_comboBox.setItemText(5, _translate("add_class_dialog", "6"))
        self.endPeriod_comboBox.setItemText(6, _translate("add_class_dialog", "7"))
        self.endPeriod_comboBox.setItemText(7, _translate("add_class_dialog", "8"))
        self.endPeriod_comboBox.setItemText(8, _translate("add_class_dialog", "9"))
        self.endPeriod_comboBox.setItemText(9, _translate("add_class_dialog", "10"))
        self.label_9.setText(_translate("add_class_dialog", "Thứ"))
        self.day_comboBox.setItemText(0, _translate("add_class_dialog", "2"))
        self.day_comboBox.setItemText(1, _translate("add_class_dialog", "3"))
        self.day_comboBox.setItemText(2, _translate("add_class_dialog", "4"))
        self.day_comboBox.setItemText(3, _translate("add_class_dialog", "5"))
        self.day_comboBox.setItemText(4, _translate("add_class_dialog", "6"))
        self.day_comboBox.setItemText(5, _translate("add_class_dialog", "7"))
        self.add_Btn.setText(_translate("add_class_dialog", "Thêm"))
        self.cancel_Btn.setText(_translate("add_class_dialog", "Hủy"))
