# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\lecturerMainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 600)
        MainWindow.setStyleSheet("background-color: #fff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.nav_bar_widget = QtWidgets.QWidget(self.centralwidget)
        self.nav_bar_widget.setMinimumSize(QtCore.QSize(150, 0))
        self.nav_bar_widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(31, 149, 239);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    text-align: left;\n"
"    height: 30px;\n"
"    border:none;\n"
"    padding-left: 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #F5FAFE;\n"
"    color:  #1F95EF;\n"
"    font-weight: bold;\n"
"}")
        self.nav_bar_widget.setObjectName("nav_bar_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.nav_bar_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.nav_bar_widget)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/default_ava.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.nav_bar_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.studentListBtn = QtWidgets.QPushButton(self.nav_bar_widget)
        self.studentListBtn.setCheckable(True)
        self.studentListBtn.setAutoExclusive(True)
        self.studentListBtn.setObjectName("studentListBtn")
        self.verticalLayout.addWidget(self.studentListBtn)
        self.lecturerListBtn = QtWidgets.QPushButton(self.nav_bar_widget)
        self.lecturerListBtn.setCheckable(True)
        self.lecturerListBtn.setAutoExclusive(True)
        self.lecturerListBtn.setObjectName("lecturerListBtn")
        self.verticalLayout.addWidget(self.lecturerListBtn)
        self.majorListBtn = QtWidgets.QPushButton(self.nav_bar_widget)
        self.majorListBtn.setCheckable(True)
        self.majorListBtn.setAutoExclusive(True)
        self.majorListBtn.setObjectName("majorListBtn")
        self.verticalLayout.addWidget(self.majorListBtn)
        self.classListBtn = QtWidgets.QPushButton(self.nav_bar_widget)
        self.classListBtn.setCheckable(True)
        self.classListBtn.setAutoExclusive(True)
        self.classListBtn.setObjectName("classListBtn")
        self.verticalLayout.addWidget(self.classListBtn)
        self.courseListBtn = QtWidgets.QPushButton(self.nav_bar_widget)
        self.courseListBtn.setCheckable(True)
        self.courseListBtn.setAutoRepeat(False)
        self.courseListBtn.setAutoExclusive(True)
        self.courseListBtn.setObjectName("courseListBtn")
        self.verticalLayout.addWidget(self.courseListBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 337, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.signoutBtn = QtWidgets.QPushButton(self.nav_bar_widget)
        self.signoutBtn.setObjectName("signoutBtn")
        self.verticalLayout_2.addWidget(self.signoutBtn)
        self.gridLayout.addWidget(self.nav_bar_widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.studentListPage = QtWidgets.QWidget()
        self.studentListPage.setObjectName("studentListPage")
        self.label_3 = QtWidgets.QLabel(self.studentListPage)
        self.label_3.setGeometry(QtCore.QRect(260, 240, 121, 81))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.studentListPage)
        self.lecturerListPage = QtWidgets.QWidget()
        self.lecturerListPage.setObjectName("lecturerListPage")
        self.label_4 = QtWidgets.QLabel(self.lecturerListPage)
        self.label_4.setGeometry(QtCore.QRect(250, 270, 111, 71))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.lecturerListPage)
        self.majorListPage = QtWidgets.QWidget()
        self.majorListPage.setObjectName("majorListPage")
        self.label_5 = QtWidgets.QLabel(self.majorListPage)
        self.label_5.setGeometry(QtCore.QRect(160, 220, 131, 61))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.majorListPage)
        self.classListPage = QtWidgets.QWidget()
        self.classListPage.setObjectName("classListPage")
        self.label_6 = QtWidgets.QLabel(self.classListPage)
        self.label_6.setGeometry(QtCore.QRect(316, 240, 71, 31))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.classListPage)
        self.courseListPage = QtWidgets.QWidget()
        self.courseListPage.setObjectName("courseListPage")
        self.label_7 = QtWidgets.QLabel(self.courseListPage)
        self.label_7.setGeometry(QtCore.QRect(280, 280, 61, 51))
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.courseListPage)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.signoutBtn.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tên"))
        self.studentListBtn.setText(_translate("MainWindow", "DS học sinh"))
        self.lecturerListBtn.setText(_translate("MainWindow", "DS giảng viên"))
        self.majorListBtn.setText(_translate("MainWindow", "DS ngành"))
        self.classListBtn.setText(_translate("MainWindow", "DS lớp"))
        self.courseListBtn.setText(_translate("MainWindow", "DS môn"))
        self.signoutBtn.setText(_translate("MainWindow", "Đăng xuất"))
        self.label_3.setText(_translate("MainWindow", "Student list"))
        self.label_4.setText(_translate("MainWindow", "Lecturer list"))
        self.label_5.setText(_translate("MainWindow", "major List"))
        self.label_6.setText(_translate("MainWindow", "class list"))
        self.label_7.setText(_translate("MainWindow", "course list"))
import ava_rc
