# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_major_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QDialog, QMessageBox

from university_management.src.controller.major_management.edit_major import editMajor
from university_management.src.controller.major_management.get_major import get_full_major_info


class Ui_update_major_dialog(QDialog):
    """
    update major dialog GUI
    """
    data_updated = pyqtSignal()
    def __init__(self, row_index, row_data):
        super().__init__()

        self.row_index = row_index
        self.row_data = row_data
        self.major_info = get_full_major_info(self.row_data[0])
        print(self.major_info)

        # get selected major info
        self.major_id_info = self.major_info[0]
        self.major_name_info = self.major_info[1]

        self.setObjectName("Dialog")
        self.resize(466, 242)
        self.setStyleSheet("QDialog {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid rgb(31, 149, 239);\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"QDateEdit {\n"
"    border: 1px solid rgb(31, 149, 239);\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 31px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid rgb(31, 149, 239);\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 31px;\n"
"}")
        self.line = QtWidgets.QFrame(self)
        self.line.setGeometry(QtCore.QRect(0, 60, 461, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 441, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.update_majorNameEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.update_majorNameEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.update_majorNameEdit.setObjectName("update_majorNameEdit")
        self.verticalLayout_5.addWidget(self.update_majorNameEdit)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.layoutWidget_2 = QtWidgets.QWidget(self)
        self.layoutWidget_2.setGeometry(QtCore.QRect(250, 190, 201, 43))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.update_Btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.update_Btn.setMinimumSize(QtCore.QSize(0, 41))
        self.update_Btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(31, 149, 239);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}")
        self.update_Btn.setObjectName("update_Btn")
        self.horizontalLayout_2.addWidget(self.update_Btn)
        self.cancel_Btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.cancel_Btn.setMinimumSize(QtCore.QSize(0, 41))
        self.cancel_Btn.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}")
        self.cancel_Btn.setObjectName("cancel_Btn")
        self.horizontalLayout_2.addWidget(self.cancel_Btn)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(20, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Tên ngành"))
        self.update_Btn.setText(_translate("Dialog", "Cập nhập"))
        self.cancel_Btn.setText(_translate("Dialog", "Hủy"))
        self.label.setText(_translate("Dialog", "Chỉnh sửa thông tin"))

        self.update_majorNameEdit.setText(str(self.major_name_info))

        self.update_Btn.clicked.connect(self.update_major)

    def update_major(self):
        """
        update major button logic
        """
        params = self.update_majorNameEdit.text()
        editMajor(self.major_id_info, params)
        self.show_updated_message()
        self.data_updated.emit()
        self.close()

    def show_updated_message(self):
        """
         show update message
        """
        msg_box = QMessageBox(self)
        msg_box.setWindowTitle("Success")
        msg_box.setText("Đã sửa thành công")
        msg_box.exec()


