# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_lecturer_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QDialog, QMessageBox

from university_management.src.controller.major_management.get_major import get_major_id, get_all_major
from university_management.src.controller.user_management.edit_user import editLecturer
from university_management.src.controller.user_management.get_user_info import get_full_lecturer_info
from university_management.src.util.getFirstAndLastName import getFirstAndLastName
from university_management.src.util.getGenderId import get_gender_id


class Ui_update_lecturer_dialog(QDialog):
    data_updated = pyqtSignal()

    def __init__(self, row_index, row_data):
        super().__init__()
        self.row_index = row_index
        self.row_data = row_data
        self.lecturer_info = get_full_lecturer_info(self.row_data[0])

        # get selected lecturer info
        self.lecturer_id_info = self.lecturer_info[0]
        self.lecturer_firstName_info = self.lecturer_info[1]
        self.lecturer_lastName_info = self.lecturer_info[2]
        self.lecturer_phone_info = self.lecturer_info[3]
        self.lecturer_address_info = self.lecturer_info[4]
        self.lecturer_gender_info = self.lecturer_info[5]
        self.lecturer_major_info = self.lecturer_info[6]

        self.setObjectName("update_student_dialog")
        self.resize(466, 517)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.setFont(font)
        self.setStyleSheet("QDialog {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid rgb(31, 149, 239);\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"QDateEdit {\n"
"    border: 1px solid rgb(31, 149, 239);\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 31px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid rgb(31, 149, 239);\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 31px;\n"
"}")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(20, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self)
        self.line.setGeometry(QtCore.QRect(0, 60, 461, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 441, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.update_lecturerIDEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.update_lecturerIDEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.update_lecturerIDEdit.setObjectName("update_lecturerIDEdit")
        self.verticalLayout.addWidget(self.update_lecturerIDEdit)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.update_lecturer_gender_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.update_lecturer_gender_comboBox.setObjectName("update_lecturer_gender_comboBox")
        self.update_lecturer_gender_comboBox.addItem("")
        self.update_lecturer_gender_comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.update_lecturer_gender_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.update_lecturer_major_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.update_lecturer_major_comboBox.setObjectName("update_lecturer_major_comboBox")
        major_list = get_all_major()
        print(len(major_list))
        for major in major_list:
            self.update_lecturer_major_comboBox.addItem(major)
        self.verticalLayout_3.addWidget(self.update_lecturer_major_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.update_lecturerNameEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.update_lecturerNameEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.update_lecturerNameEdit.setObjectName("update_lecturerNameEdit")
        self.verticalLayout_5.addWidget(self.update_lecturerNameEdit)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.update_lecturerPhoneEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.update_lecturerPhoneEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.update_lecturerPhoneEdit.setObjectName("update_lecturerPhoneEdit")
        self.verticalLayout_6.addWidget(self.update_lecturerPhoneEdit)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.update_lecturerAddressEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.update_lecturerAddressEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.update_lecturerAddressEdit.setObjectName("update_lecturerAddressEdit")
        self.verticalLayout_7.addWidget(self.update_lecturerAddressEdit)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.layoutWidget1 = QtWidgets.QWidget(self)
        self.layoutWidget1.setGeometry(QtCore.QRect(250, 460, 201, 43))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.update_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.update_Btn.setMinimumSize(QtCore.QSize(0, 41))
        self.update_Btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(31, 149, 239);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}")
        self.update_Btn.setObjectName("update_Btn")
        self.horizontalLayout_2.addWidget(self.update_Btn)
        self.update_cancel_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.update_cancel_Btn.setMinimumSize(QtCore.QSize(0, 41))
        self.update_cancel_Btn.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}")
        self.update_cancel_Btn.setObjectName("update_cancel_Btn")
        self.horizontalLayout_2.addWidget(self.update_cancel_Btn)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, update_student_dialog):
        _translate = QtCore.QCoreApplication.translate
        update_student_dialog.setWindowTitle(_translate("update_student_dialog", "Dialog"))
        self.label.setText(_translate("update_student_dialog", "Cập nhập thông tin"))
        self.label_2.setText(_translate("update_student_dialog", "Mã số giảng viên"))
        self.label_5.setText(_translate("update_student_dialog", "Giới tính"))
        self.update_lecturer_gender_comboBox.setItemText(0, _translate("update_student_dialog", "Nam"))
        self.update_lecturer_gender_comboBox.setItemText(1, _translate("update_student_dialog", "Nữ"))
        self.label_6.setText(_translate("update_student_dialog", "Ngành"))
        self.label_3.setText(_translate("update_student_dialog", "Họ tên"))
        self.label_4.setText(_translate("update_student_dialog", "Số điện thoại"))
        self.label_8.setText(_translate("update_student_dialog", "Địa chỉ"))
        self.update_Btn.setText(_translate("update_student_dialog", "Cập nhập"))
        self.update_cancel_Btn.setText(_translate("update_student_dialog", "Hủy"))

        self.update_lecturerIDEdit.setText(str(self.lecturer_id_info))
        self.update_lecturerNameEdit.setText(str(self.lecturer_lastName_info) + " " + str(self.lecturer_firstName_info))
        self.update_lecturer_gender_comboBox.setCurrentText(str(self.lecturer_gender_info))
        self.update_lecturer_major_comboBox.setCurrentText(str(self.lecturer_major_info))
        self.update_lecturerPhoneEdit.setText(str(self.lecturer_phone_info))
        self.update_lecturerAddressEdit.setText(str(self.lecturer_address_info))

        self.update_Btn.clicked.connect(self.update_lecturer)

        #Get major update signal to update comboBox
        from loadLecturerMS import LecturerMainScreen
        self.update_major = LecturerMainScreen()
        self.update_major.majorListUpdated.connect(self.update_major_comboBox)

    def update_lecturer(self):
        new_last_name ,new_first_name = getFirstAndLastName(self.update_lecturerNameEdit.text())
        params = {
            "new_id": self.update_lecturerIDEdit.text(),
            "new_gender": get_gender_id(self.update_lecturer_gender_comboBox.currentText()),
            "new_major": get_major_id(self.update_lecturer_major_comboBox.currentText()),
            "new_email": self.update_lecturerIDEdit.text() + "@gm.uit.edu.vn",
            "new_last_name": new_last_name,
            "new_first_name": new_first_name,
            "new_telephone": self.update_lecturerPhoneEdit.text(),
            "new_address": self.update_lecturerAddressEdit.text()
        }

        editLecturer(self.lecturer_id_info, params)
        self.show_updated_message()

        self.data_updated.emit()
        self.close()

    def show_updated_message(self):
        msg_box = QMessageBox(self)
        msg_box.setWindowTitle("Success")
        msg_box.setText("Đã sửa thành công")
        msg_box.exec()

    def update_major_comboBox(self, new_major_list):
        self.update_lecturer_major_comboBox.clear()
        for major in new_major_list:
            self.update_lecturer_major_comboBox.addItem(major)